### ISSUE TITLE
Sequelize should be a peer dependency

### ISSUE THREAD

**Issue by mikefrey** [danecando/hapi-sequelized#19]
Sequelize should be included as a peer dependency, rather than a normal dependency. That way it's guaranteed that the cli and the hapi plugin both use the exact same sequelize version.

**Comment by danecando** [comment]
@mikefrey this would require you to run the cli inside of the plugin directory, correct?

**Comment by mikefrey** [comment]
Without it set as a peer dependency, you must run the cli from `youApp/node_modules/hapi-sequelized` and specify the `--config` and `--migration-path` options.

**Comment by danecando** [comment]
@mikefrey when I don't have sequelize installed in the root of my project and have it set as a peer dependency inside of the plugin I get the error: Unable to resolve sequelize package in /my/project/root when trying to use the CLI

**Comment by mikefrey** [comment]
Exactly. That is the intended behavior. Your project should have a direct dependency on Sequelize. The project should set the version of Sequelize that is used, not the plugin.

**Comment by danecando** [comment]
@mikefrey great just wanted to check. I setup a nice flow in my project using the update that I just pushed to the v2 branch with migrations and all the other features (new to the cli and migrations). Thanks for your contributions!

**Comment by duro** [comment]
Was this change dropped from being implemented? I still see sequelize as a core dependency, and I agree this should be a peerDependency.
